smtp:
    image: ryangraham/postfix-mailgun
    environment:
        # Get your credentials at https://mailgun.com
        MG_USER: xxxxx
        MG_PASS: xxxxx

mysql:
    image: mysql:5.6
    environment:
        MYSQL_DATABASE: streama
        MYSQL_ROOT_PASSWORD: root

web:
    image: r0lhw/docker-streama
    environment:
        DATABASE_HOST: mysql
        STREAMA_DB_NAME: streama
        STREAMA_DB_USER: root
        STREAMA_DB_PASSWORD: root
    ports:
    - 80:8080
    links:
    - mysql
    - smtp
