mysql:
    image: mysql:5.6
    environment:
        MYSQL_DATABASE: streama
        MYSQL_ROOT_PASSWORD: root

web:
    image: r0lhw/docker-streama
    environment:
        DATABASE_HOST: mysql
        STREAMA_DB_NAME: streama
        STREAMA_DB_USER: root
        STREAMA_DB_PASSWORD: root
    ports:
    - 80:8080
    links:
    - mysql
